[webservers]
app-1 ansible_host=213.171.25.250 ansible_user=ubuntu ansible_ssh_private_key_file=/home/cruel/.ssh/id_rsa_new ansible_ssh_common_args='-o ConnectTimeout=60 -o ServerAliveInterval=60'
app-2 ansible_host=176.108.250.27 ansible_user=ubuntu ansible_ssh_private_key_file=/home/cruel/.ssh/id_rsa_new ansible_ssh_common_args='-o ConnectTimeout=60 -o ServerAliveInterval=60'

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_become=yes